# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: env.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'env.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tenv.proto\x12\x0cneurogenesis\";\n\x0bObservation\x12\x0e\n\x06tensor\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"6\n\x06\x41\x63tion\x12\x0e\n\x06tensor\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"\x0e\n\x0cResetRequest\"?\n\rResetResponse\x12.\n\x0bobservation\x18\x01 \x01(\x0b\x32\x19.neurogenesis.Observation\"3\n\x0bStepRequest\x12$\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x14.neurogenesis.Action\"\\\n\x0cStepResponse\x12.\n\x0bobservation\x18\x01 \x01(\x0b\x32\x19.neurogenesis.Observation\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"\x1b\n\x0bSeedRequest\x12\x0c\n\x04seed\x18\x01 \x01(\x03\"\x0e\n\x0cSeedResponse\")\n\tSpaceSpec\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x64type\x18\x02 \x01(\t\"\r\n\x0bSpecRequest\"e\n\x0cSpecResponse\x12,\n\x0bobservation\x18\x01 \x01(\x0b\x32\x17.neurogenesis.SpaceSpec\x12\'\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x17.neurogenesis.SpaceSpec2\x84\x02\n\x03\x45nv\x12@\n\x05Reset\x12\x1a.neurogenesis.ResetRequest\x1a\x1b.neurogenesis.ResetResponse\x12=\n\x04Step\x12\x19.neurogenesis.StepRequest\x1a\x1a.neurogenesis.StepResponse\x12=\n\x04Seed\x12\x19.neurogenesis.SeedRequest\x1a\x1a.neurogenesis.SeedResponse\x12=\n\x04Spec\x12\x19.neurogenesis.SpecRequest\x1a\x1a.neurogenesis.SpecResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'env_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=27
  _globals['_OBSERVATION']._serialized_end=86
  _globals['_ACTION']._serialized_start=88
  _globals['_ACTION']._serialized_end=142
  _globals['_RESETREQUEST']._serialized_start=144
  _globals['_RESETREQUEST']._serialized_end=158
  _globals['_RESETRESPONSE']._serialized_start=160
  _globals['_RESETRESPONSE']._serialized_end=223
  _globals['_STEPREQUEST']._serialized_start=225
  _globals['_STEPREQUEST']._serialized_end=276
  _globals['_STEPRESPONSE']._serialized_start=278
  _globals['_STEPRESPONSE']._serialized_end=370
  _globals['_SEEDREQUEST']._serialized_start=372
  _globals['_SEEDREQUEST']._serialized_end=399
  _globals['_SEEDRESPONSE']._serialized_start=401
  _globals['_SEEDRESPONSE']._serialized_end=415
  _globals['_SPACESPEC']._serialized_start=417
  _globals['_SPACESPEC']._serialized_end=458
  _globals['_SPECREQUEST']._serialized_start=460
  _globals['_SPECREQUEST']._serialized_end=473
  _globals['_SPECRESPONSE']._serialized_start=475
  _globals['_SPECRESPONSE']._serialized_end=576
  _globals['_ENV']._serialized_start=579
  _globals['_ENV']._serialized_end=839
# @@protoc_insertion_point(module_scope)
